import os
from dotenv import load_dotenv
load_dotenv()
MAX_CONCURRENT_THREADS = int(os.getenv("MAX_CONCURRENT_THREADS", 10))
MAX_PAGES_PER_THREAD = int(os.getenv("MAX_PAGES_PER_THREAD", 10))
FULL_LOGGING = bool(os.getenv("FULL_LOGGING") == "True" or False)

AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION")
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_DEPLOYMENT_NAME = os.getenv("AZURE_OPENAI_DEPLOYMENT_NAME")